export const ROOTS = [
  {
    id: 1,
    title: "Muscle Fiber Architecture and Force Production",
    rootQuestion: `A sprinter and a marathon runner have identical total quadriceps muscle volume confirmed by MRI. During a maximal sprint the sprinter produces 340 watts of peak power. The marathon runner produces 180 watts peak power from the same muscle volume. Neither athlete is injured. Explain the specific structural difference in muscle fiber composition that accounts for this power differential, explain why fiber type produces this difference mechanistically rather than just correlating with it, and predict what would happen to each athlete's power output and fatigue rate if both performed a 45-minute moderate intensity cycling session immediately before the sprint test.`,
    branches: [
      {
        label: "Edge Case",
        question: `A previously sedentary person begins a 16-week resistance training program. Muscle biopsies taken before and after show no significant change in the ratio of Type I to Type II fibers. Yet their peak power output has increased by 35 percent. Explain the specific structural and neural adaptations that produced this power increase without fiber type conversion, and predict which of these adaptations reached its ceiling first.`
      },
      {
        label: "Cross-Root Integration",
        question: `The sprinter from the root question also has a significantly higher testosterone response to resistance training than the marathon runner. Using your understanding of both muscle fiber architecture and hormonal response to exercise, predict how the hormonal difference interacts with the existing fiber type composition to affect hypertrophy potential in each athlete, and explain why the same hormonal signal produces different structural outcomes in fiber-type-different muscles.`
      },
      {
        label: "Counterintuitive Prediction",
        question: `A muscle biopsy of an elite powerlifter shows that 60 percent of their vastus lateralis fibers are Type I slow-twitch despite their sport demanding maximal force production. Explain why this finding is less surprising than it initially appears, identify the specific training characteristic of powerlifting that selects for this fiber composition, and predict how this powerlifter's performance would compare to a sprinter on a test of maximal force production versus rate of force development.`
      }
    ],
    rubric: "Criterion 1: Identifies Type I versus Type II fiber distinction as the structural mechanism accounting for the power differential — not training history, motivation, or total muscle volume. Criterion 2: Connects fiber type to contractile speed and fatigue resistance mechanistically — explains why the structural difference produces the power difference, not just that it correlates with it. Criterion 3: Predicts the pre-fatigue effect on the sprinter specifically using fiber type logic — Type II depletion reducing peak power output. Criterion 4: Predicts the pre-fatigue effect on the marathon runner specifically using fiber type logic — Type I dominance meaning relatively less power loss from the same protocol."
  },
  {
    id: 2,
    title: "Energy Systems and Their Interaction",
    rootQuestion: `A cyclist is performing a 20-minute time trial at maximum sustainable effort. At the 30-second mark their power output is 420 watts. At the 5-minute mark it has dropped to 310 watts. At the 15-minute mark it has stabilized at 285 watts. They are not pacing — they are going as hard as possible at each moment. Explain the specific energy system transitions that account for this power output curve, identify the metabolic event that causes the drop from 420 to 310 watts specifically, and predict what the power output curve would look like if the same athlete performed the same test after 3 days of carbohydrate restriction to deplete muscle glycogen.`,
    branches: [
      {
        label: "Edge Case",
        question: `Two athletes have identical VO2 max values of 65 ml/kg/min. In a 10km race one athlete runs 32 minutes and the other runs 38 minutes. Using energy system principles explain what specific metabolic variable best explains this performance difference despite identical maximal aerobic capacity, and predict how each athlete's lactate curve would look during an incremental exercise test.`
      },
      {
        label: "Cross-Root Integration",
        question: `The phosphocreatine system and the glycolytic system both contribute to a 400-meter sprint. Using your understanding of energy systems and muscle fiber architecture predict how the relative contribution of each system changes across the 400 meters, explain why the dramatic slowdown in the final 100 meters of most 400-meter races is a metabolic event not a motivational one, and identify the specific metabolic accumulation that drives this slowdown.`
      },
      {
        label: "Counterintuitive Prediction",
        question: `An endurance athlete performs 8 weeks of sprint interval training — 6 second maximal sprints with 4 minute recovery — with no changes to their steady-state aerobic training. Their 10km race time improves by 90 seconds despite the interval training never stressing their aerobic system significantly. Explain the specific adaptations from sprint interval training that improve endurance performance through a non-aerobic mechanism.`
      }
    ],
    rubric: "Criterion 1: Correctly identifies all three energy system transitions across the time trial — PCr system dominant at 30 seconds, glycolytic system dominant at 5 minutes, aerobic system stabilizing at 15 minutes. Criterion 2: Identifies PCr depletion specifically as the metabolic event causing the drop from 420 to 310 watts — not glycogen depletion, not lactate, not general fatigue. Criterion 3: Predicts the glycogen depletion effect on aerobic contribution correctly — reduced glycolytic substrate forces greater reliance on fat oxidation, lowering sustainable power output. Criterion 4: Predicts the glycogen depletion effect on anaerobic contribution correctly — glycolytic system is severely impaired from the start, eliminating the early high-power phase."
  },
  {
    id: 3,
    title: "Neuromuscular Activation and Motor Unit Recruitment",
    rootQuestion: `A powerlifter attempts a maximal deadlift of 250kg — a weight they have lifted before. On the first attempt they fail at the sticking point. On the second attempt 4 minutes later they successfully complete the lift. Their muscle strength has not changed between attempts. Explain the specific neuromuscular mechanism that allowed the second attempt to succeed where the first failed, identify what changed in the nervous system between attempts rather than in the muscle, and predict what would happen to their maximal lift capacity if they performed 30 minutes of light cardio immediately before the third attempt.`,
    branches: [
      {
        label: "Edge Case",
        question: `A stroke patient has lost the ability to voluntarily activate the left bicep despite the muscle being completely intact — no atrophy, normal histology, normal response to direct electrical stimulation. Yet when the patient yawns, the left bicep contracts involuntarily. Explain the specific neurological distinction between voluntary and involuntary motor activation that accounts for this pattern, and predict what rehabilitation approach would most efficiently restore voluntary control.`
      },
      {
        label: "Cross-Root Integration",
        question: `Elite weightlifters produce higher peak forces than equally strong powerlifters during ballistic movements despite having similar one-rep max scores. Using your understanding of both motor unit recruitment and muscle fiber architecture explain the specific neuromuscular characteristic that accounts for this difference in rate of force development, and predict how training each quality specifically changes the recruitment pattern over time.`
      },
      {
        label: "Counterintuitive Prediction",
        question: `A researcher measures motor unit recruitment during a set of bicep curls taken to failure with a light weight — 30 percent of one rep max. Early in the set only low-threshold motor units are active. By the final repetitions before failure, high-threshold motor units are fully recruited despite the load being only 30 percent of maximum. Explain the specific mechanism that forces high-threshold motor unit recruitment at low loads when taken to failure, and predict the hypertrophy stimulus of this protocol compared to a heavy set at 85 percent of one rep max stopped well short of failure.`
      }
    ],
    rubric: "Criterion 1: Identifies rate coding — increased motor unit firing frequency — as a specific mechanism that changed between attempts rather than muscle strength. Criterion 2: Identifies motor unit synchronization or recruitment pattern improvement as a second specific neural mechanism that changed between attempts. Criterion 3: Addresses post-activation potentiation explicitly as the named mechanism responsible for the second attempt success. Criterion 4: Predicts the cardio effect using neural fatigue as the mechanism — light cardio impairs CNS output capacity without fatiguing the muscles themselves, reducing maximal recruitment on the third attempt."
  },
  {
    id: 4,
    title: "Acute Hormonal Response to Training",
    rootQuestion: `Two athletes perform resistance training sessions of identical volume — same exercises, sets, reps, and total tonnage. Athlete A performs the session as straight sets with 3 minutes rest between sets over 60 minutes. Athlete B performs the same volume as supersets with 60 seconds rest between exercises over 35 minutes. Blood samples taken immediately after each session show dramatically different hormonal profiles — Athlete B has significantly higher testosterone, growth hormone, and cortisol. Both athletes have trained for 5 years. Explain the specific training variable that drives the hormonal difference, predict whether the higher hormonal response in Athlete B produces greater muscle protein synthesis over the following 48 hours, and explain why the answer to that prediction is less straightforward than it initially appears.`,
    branches: [
      {
        label: "Edge Case",
        question: `A 45-year-old male athlete has resting testosterone levels 40 percent below the normal range for his age despite excellent health, nutrition, and sleep. His resistance training produces a normal acute hormonal response — testosterone rises appropriately during and after training. Yet his hypertrophy response to training over 12 weeks is significantly blunted compared to age-matched peers with normal testosterone. Explain the specific mechanism by which chronically low resting testosterone blunts hypertrophy despite normal acute response, and identify at what point in the muscle protein synthesis cascade the deficit manifests.`
      },
      {
        label: "Cross-Root Integration",
        question: `Cortisol rises acutely during both resistance training and endurance training. Using your understanding of hormonal response and energy systems explain why acute cortisol elevation during training serves a different metabolic function in resistance versus endurance contexts, predict the consequence of chronically elevated resting cortisol on muscle protein balance, and explain why the timing of cortisol elevation relative to anabolic hormones determines whether the net effect is catabolic or anabolic.`
      },
      {
        label: "Counterintuitive Prediction",
        question: `Two athletes have identical training programs and nutrition. Athlete A sleeps 8 hours per night consistently. Athlete B sleeps 5.5 hours per night. After 12 weeks Athlete B has gained significantly less muscle despite identical training stimulus and caloric intake. A muscle biopsy shows identical rates of muscle protein synthesis in both athletes measured immediately after training sessions. Explain where in the 24-hour recovery cycle the hormonal difference between athletes is producing the divergent outcomes, and predict the specific hormonal measurement that would most clearly explain the difference.`
      }
    ],
    rubric: "Criterion 1: Identifies metabolic stress — byproduct accumulation from higher training density — as the specific training variable driving Athlete B's higher hormonal response despite identical volume. Criterion 2: Addresses the distinction between acute hormonal spike and chronic anabolic environment — correctly identifies that a larger acute response does not automatically produce greater muscle protein synthesis over 48 hours. Criterion 3: Predicts sleep deprivation effect at the hormonal synthesis level — specifically nocturnal growth hormone secretion loss — not just at the training stimulus level. Criterion 4: Explains why the prediction is less straightforward than it appears — the relationship between acute hormonal peaks and downstream hypertrophy is not linear and depends on receptor sensitivity and chronic hormonal environment."
  },
  {
    id: 5,
    title: "Muscle Protein Synthesis and the Hypertrophy Signal",
    rootQuestion: `A researcher gives two groups of subjects identical resistance training programs for 16 weeks. Group A consumes 1.6 grams of protein per kilogram of bodyweight daily evenly distributed across 4 meals. Group B consumes the same total daily protein in 2 meals — a small breakfast and a large dinner. Both groups gain strength equally. Group A gains significantly more muscle mass. Explain the specific molecular mechanism by which protein distribution affects muscle protein synthesis independent of total protein intake, identify the signaling pathway that is differentially activated, and predict the minimum meal protein dose required to maximally stimulate this pathway in a trained individual versus an untrained individual.`,
    branches: [
      {
        label: "Edge Case",
        question: `A bodybuilder tears their left bicep completely at the musculotendinous junction and undergoes surgical repair. During the 12-week immobilization period they continue training the right arm intensively. At 12 weeks the right arm has gained 2cm of circumference. Surprisingly the left arm, while atrophied, has lost less muscle than predicted by immobilization research. Explain the specific mechanism by which intensive unilateral training attenuates contralateral muscle atrophy, identify the neural and systemic pathways responsible, and predict whether this cross-education effect is sufficient to meaningfully affect rehabilitation outcomes.`
      },
      {
        label: "Cross-Root Integration",
        question: `mTORC1 is the primary anabolic signaling hub for muscle protein synthesis. Both resistance exercise and leucine from dietary protein activate mTORC1. Using your understanding of muscle protein synthesis and hormonal response to training explain why combining resistance exercise and protein intake produces greater mTORC1 activation than either stimulus alone, predict the optimal timing window between training and protein intake for maximal synergistic activation, and explain why this timing effect diminishes in highly trained individuals compared to beginners.`
      },
      {
        label: "Counterintuitive Prediction",
        question: `A study compares two hypertrophy programs over 6 months. Program A uses traditional progressive overload — adding weight each week. Program B keeps weight constant but increases reps until a set becomes easy then adds a small weight increment. Both programs equate total volume. At 6 months muscle biopsies show identical hypertrophy. However subjects in Program B report significantly lower perceived exertion and better recovery. Explain why identical hypertrophy outcomes are possible through mechanically different loading approaches, identify what the actual driver of the hypertrophic stimulus is in both programs, and predict which program would produce greater strength gains despite identical hypertrophy.`
      }
    ],
    rubric: "Criterion 1: Identifies leucine threshold as the specific molecular mechanism — each meal must contain sufficient leucine to cross the activation threshold for mTORC1. Criterion 2: Identifies mTORC1 as the specific signaling pathway that is differentially activated by distributed versus concentrated protein intake. Criterion 3: Connects protein distribution to pulsatile mTORC1 activation — more meals crossing the leucine threshold means more discrete activation pulses versus one large pulse and prolonged sub-threshold levels. Criterion 4: Addresses the trained versus untrained leucine threshold difference — trained individuals require a higher leucine dose per meal to maximally stimulate mTORC1."
  },
  {
    id: 6,
    title: "Cardiovascular Adaptation to Endurance Training",
    rootQuestion: `An untrained 25-year-old begins an 8-month endurance training program. At baseline their resting heart rate is 72 bpm, stroke volume is 70ml, and VO2 max is 38 ml/kg/min. After 8 months their resting heart rate is 48 bpm, stroke volume is 105ml, and VO2 max is 52 ml/kg/min. Their maximum heart rate has not changed. Explain the specific structural cardiac adaptation that accounts for the stroke volume increase, explain why resting heart rate decreases as a mathematical consequence of stroke volume increase rather than as an independent adaptation, and predict what happens to each of these three variables during the first 3 weeks of complete detraining.`,
    branches: [
      {
        label: "Edge Case",
        question: `A competitive cyclist with a VO2 max of 72 ml/kg/min and resting heart rate of 38 bpm develops a cardiac arrhythmia requiring a pacemaker set at a fixed rate of 70 bpm. Their maximum achievable heart rate is now 70 bpm — well below the normal maximum. Predict their new VO2 max and explain the specific cardiovascular equation that determines this value, identify which component of the Fick equation is most limiting in this scenario, and predict how this athlete's performance across different event durations — sprint versus middle distance versus ultra-endurance — changes relative to their pre-pacemaker capacity.`
      },
      {
        label: "Cross-Root Integration",
        question: `Endurance training and resistance training produce opposing cardiac adaptations — eccentric versus concentric hypertrophy. Using your understanding of cardiovascular adaptation and the energy systems explain why the mechanical demand of each training modality produces structurally opposite cardiac responses, predict the cardiac morphology of an athlete who trains both modalities equally at high volume, and explain why the combined cardiac phenotype is actually advantageous rather than a compromise.`
      },
      {
        label: "Counterintuitive Prediction",
        question: `A 50-year-old sedentary individual begins endurance training and after one year achieves a VO2 max of 45 ml/kg/min — above average for their age. An elite 20-year-old endurance athlete has a VO2 max of 78 ml/kg/min. The older trained individual's cardiac output at maximal exercise is actually higher relative to their VO2 max than the elite athlete's. Explain the specific cardiovascular variable that accounts for this — why the older trained individual needs more cardiac output per unit of oxygen consumed than the elite athlete — and predict what peripheral adaptation in the elite athlete explains their superior oxygen extraction efficiency.`
      }
    ],
    rubric: "Criterion 1: Identifies eccentric cardiac hypertrophy — increased end-diastolic volume — as the specific structural cardiac adaptation accounting for the stroke volume increase. Criterion 2: Derives resting heart rate decrease mathematically from stroke volume increase using the cardiac output equation — cardiac output at rest stays constant so heart rate must fall as stroke volume rises — not as an independent adaptation. Criterion 3: Predicts the detraining sequence for stroke volume correctly — reverses relatively quickly within 1 to 2 weeks as plasma volume decreases. Criterion 4: Predicts the detraining sequence for VO2 max correctly — declines more slowly than stroke volume because peripheral adaptations persist longer than central cardiac changes."
  },
  {
    id: 7,
    title: "Connective Tissue Adaptation",
    rootQuestion: `A 28-year-old recreational runner increases their weekly mileage from 30km to 60km over 6 weeks in preparation for a marathon. At week 5 they develop Achilles tendinopathy — pain and morning stiffness at the Achilles tendon insertion. Their cardiovascular fitness has improved normally throughout this period. The tendon has not ruptured. Explain the specific structural reason why connective tissue adaptation lags behind cardiovascular and muscular adaptation during rapid training load increases, identify the cellular mechanism responsible for tendon remodeling and why it is rate-limited, and predict what training modification would allow this athlete to reach 60km per week without developing tendinopathy given a longer timeline.`,
    branches: [
      {
        label: "Edge Case",
        question: `Two athletes sustain identical grade 2 medial collateral ligament sprains of the knee. Athlete A has been resistance training for 6 years. Athlete B has been sedentary. MRI confirms equivalent ligament damage in both. At 12 weeks Athlete A has returned to full sport while Athlete B is still in rehabilitation. Both athletes had identical rehabilitation programs. Explain the specific pre-injury structural differences in Athlete A's ligament that account for the faster recovery, identify the cellular mechanism that produced these structural differences through training, and predict whether the recovered ligament in Athlete A returns to its pre-injury structural quality.`
      },
      {
        label: "Cross-Root Integration",
        question: `Heavy resistance training produces both muscular hypertrophy and increased tendon stiffness. Using your understanding of connective tissue adaptation and neuromuscular activation explain why increased tendon stiffness is actually advantageous for force production rather than simply being a parallel adaptation, identify the specific mechanical property of stiff tendons that enhances rate of force development, and predict the performance consequence for an athlete who has high muscular strength but undertrained tendon stiffness.`
      },
      {
        label: "Counterintuitive Prediction",
        question: `A researcher compares tendon collagen synthesis rates in athletes performing heavy resistance training versus moderate intensity endurance training matched for total lower limb mechanical loading. The endurance training group shows higher rates of tendon collagen synthesis despite lower peak forces. Explain the specific loading characteristic — not peak force — that most strongly drives tendon collagen synthesis, identify what property of cyclical loading at moderate force is a stronger collagen synthesis stimulus than infrequent loading at high force, and predict the optimal tendon conditioning protocol for an athlete returning from tendon injury.`
      }
    ],
    rubric: "Criterion 1: Identifies tenocyte remodeling rate as the rate-limiting factor — tenocytes synthesize and remodel collagen more slowly than muscle cells hypertrophy or cardiovascular adaptations occur. Criterion 2: Explains the vascularity deficit of tendon compared to muscle as the mechanistic basis of slower adaptation — lower blood supply means slower delivery of nutrients and signaling molecules to tenocytes. Criterion 3: Predicts the correct training modification using load management principles — a longer ramp-up timeline with smaller weekly mileage increases rather than rest or complete load avoidance. Criterion 4: Connects the load management prediction to the tenocyte mechanism — slower load increase gives tenocytes sufficient time to synthesize collagen and remodel the tendon matrix between loading sessions."
  },
  {
    id: 8,
    title: "Training Principles: Overload, Specificity, and Recovery",
    rootQuestion: `Two athletes both want to improve their 400-meter sprint time. Athlete A runs 400-meter repeats at race pace 4 times per week. Athlete B runs a variety of distances — 100m, 200m, 400m, and 800m repeats — at varied intensities 5 times per week with one session per week of heavy resistance training. After 16 weeks Athlete A has improved their 400m time by 1.8 seconds. Athlete B has improved by 3.1 seconds. Both athletes recovered well with no injuries. Explain the specific training principle that accounts for Athlete B's superior improvement despite less specific training, predict which athlete has a higher ceiling for further improvement at the 400-meter distance, and explain why the optimal specificity ratio changes as an athlete approaches their genetic potential.`,
    branches: [
      {
        label: "Edge Case",
        question: `A highly trained athlete takes a planned 4-week complete rest period — no training whatsoever. At the end of 4 weeks their VO2 max has dropped by 8 percent, their strength has dropped by 4 percent, and their body composition has changed minimally. They resume training and within 3 weeks are back to all baseline measures. Explain the specific mechanisms that allow such rapid restoration of fitness, identify what structural adaptations are genuinely lost versus simply suppressed during detraining, and predict how the detraining and retraining response would differ for an athlete who takes a 6-month break rather than 4 weeks.`
      },
      {
        label: "Cross-Root Integration",
        question: `Progressive overload requires continually increasing training stress to drive adaptation. Using your understanding of both training principles and hormonal response explain why linear progressive overload — adding weight every session — works well for beginners but produces diminishing returns and increasing injury risk for advanced athletes, identify the specific hormonal and structural reason the adaptation curve flattens, and predict the optimal periodization structure for an advanced athlete that maintains progressive overload without requiring linear load increases every session.`
      },
      {
        label: "Counterintuitive Prediction",
        question: `A strength athlete reduces their training volume by 40 percent for 3 weeks while maintaining training intensity — same weights, fewer sets. At the end of the taper their performance on a maximal strength test improves by 6 percent compared to their pre-taper baseline. Explain the specific physiological mechanism by which reducing training volume while maintaining intensity produces a performance increase rather than a decrease, identify what was accumulating during the high-volume training phase that was masking true strength capacity, and predict the optimal taper duration and volume reduction percentage for maximizing this effect.`
      }
    ],
    rubric: "Criterion 1: Identifies varied stimulus as the specific mechanism behind Athlete B's superior improvement — different distances and intensities stress different energy systems and neuromuscular qualities producing broader adaptation. Criterion 2: Addresses the specificity-variability tradeoff explicitly — explains why less specific training produced better results at this stage of training development. Criterion 3: Predicts which athlete has a higher ceiling correctly — Athlete B, because their broader adaptation base leaves more room for specific refinement while Athlete A has already been highly specific and faces diminishing returns. Criterion 4: Explains why the optimal specificity ratio changes as an athlete approaches genetic potential — advanced athletes need broader stimulus for continued adaptation while beginners benefit from almost any specific stimulus."
  }
];

export const DICTIONARY = {
  1: [
    { term: 'Type I Fiber', definition: 'A slow-twitch muscle fiber that produces moderate force but resists fatigue. Powered primarily by oxygen.', why: 'The marathon runner\'s quadriceps are dominated by these, which is why they can sustain effort for hours but can\'t match the sprinter\'s peak power.' },
    { term: 'Type II Fiber', definition: 'A fast-twitch muscle fiber that produces high force rapidly but fatigues quickly. Powered primarily by stored glucose.', why: 'The sprinter\'s power advantage comes almost entirely from a higher proportion of these fibers in the same muscle volume.' },
    { term: 'Motor Unit', definition: 'A single motor neuron and all the muscle fibers it controls. The basic unit of muscle activation.', why: 'The nervous system recruits motor units in order of size, which determines how force output scales with effort.' },
    { term: 'Myofibril', definition: 'The contractile structure inside a muscle fiber containing the actin and myosin proteins that generate force.', why: 'More myofibrils per fiber means more force-generating capacity independent of fiber type.' },
    { term: 'Sarcomere', definition: 'The smallest contractile unit of a myofibril. Shortens during contraction by actin and myosin sliding past each other.', why: 'Understanding sarcomere mechanics is the foundation for understanding all muscle force production.' },
    { term: 'Fatigue Resistance', definition: 'The ability of a muscle fiber to maintain force output over repeated contractions.', why: 'It is the core functional difference between Type I and Type II fibers and explains the sprinter-marathon runner power differential directly.' },
    { term: 'Oxidative Capacity', definition: 'The ability of a muscle fiber to produce ATP using oxygen. Higher in Type I fibers.', why: 'Determines how long a fiber can sustain activity before force drops.' },
    { term: 'Glycolytic Capacity', definition: 'The ability of a muscle fiber to produce ATP rapidly from stored glucose without oxygen. Higher in Type II fibers.', why: 'Enables the explosive power output of sprinting but produces fatigue-causing byproducts quickly.' },
    { term: 'Fiber Type Composition', definition: 'The ratio of Type I to Type II fibers in a given muscle. Largely genetically determined.', why: 'It is the structural explanation for the power differential in the root question.' },
    { term: 'Pennation Angle', definition: 'The angle at which muscle fibers attach to the tendon. Higher angles allow more fibers in the same muscle volume.', why: 'Affects force production independent of fiber type and is relevant to understanding why muscle volume alone doesn\'t predict power output.' },
  ],
  2: [
    { term: 'ATP', definition: 'Adenosine triphosphate. The universal energy currency of the cell. Every muscular contraction requires it.', why: 'All three energy systems exist solely to regenerate ATP at different rates and durations.' },
    { term: 'Phosphocreatine System', definition: 'Regenerates ATP almost instantly from stored creatine phosphate. Lasts approximately 10 seconds at maximum effort.', why: 'Powers the first explosive seconds of the time trial before other systems take over.' },
    { term: 'Glycolytic System', definition: 'Regenerates ATP rapidly from stored muscle glycogen without oxygen. Produces hydrogen ions as a byproduct.', why: 'The primary system from approximately 10 seconds to 2 minutes of maximal effort and the source of the power drop in the root question.' },
    { term: 'Aerobic System', definition: 'Regenerates ATP using oxygen and stored fuels. Slow to reach full capacity but highly sustainable.', why: 'The stabilized power output at 15 minutes in the root question reflects this system reaching its steady state contribution.' },
    { term: 'VO2 Max', definition: 'Maximum rate of oxygen consumption during exercise. The ceiling of aerobic energy production.', why: 'Determines the upper limit of sustainable aerobic power output but does not explain performance differences between athletes with identical values.' },
    { term: 'Lactate Threshold', definition: 'The exercise intensity at which lactate begins accumulating in the blood faster than it can be cleared.', why: 'The metabolic variable that best explains the 6 minute performance gap between athletes with identical VO2 max values in Branch 1.' },
    { term: 'Glycogen', definition: 'The stored form of carbohydrate in muscle and liver. Primary fuel for the glycolytic system.', why: 'Its depletion through carbohydrate restriction in the root question directly impairs the glycolytic system\'s contribution to power output.' },
    { term: 'Hydrogen Ions', definition: 'Byproduct of glycolytic ATP production. Accumulate during high intensity exercise and impair muscle contractility.', why: 'Their accumulation is the specific mechanism driving the power drop from 420 to 310 watts in the root question.' },
    { term: 'Energy System Continuum', definition: 'The principle that all three energy systems contribute simultaneously to ATP production, with their relative contributions shifting based on intensity and duration.', why: 'The root question power curve only makes sense through this lens.' },
    { term: 'Metabolic Fatigue', definition: 'Force reduction caused by metabolic byproduct accumulation rather than structural muscle damage.', why: 'Explains why the 400 meter slowdown in Branch 2 is a metabolic event not a motivational one.' },
  ],
  3: [
    { term: 'Motor Unit Recruitment', definition: 'The process of activating motor units to produce force. More units recruited means more force produced.', why: 'What changed between the first and second deadlift attempt was recruitment quality not muscle strength.' },
    { term: 'Rate Coding', definition: 'Increasing the firing frequency of already-recruited motor units to increase force output.', why: 'Alongside recruitment it is the primary mechanism of the post-activation potentiation effect between deadlift attempts.' },
    { term: 'Post-Activation Potentiation', definition: 'Temporary enhancement of force production following a prior maximal or near-maximal contraction.', why: 'The specific neuromuscular mechanism that allowed the second deadlift attempt to succeed where the first failed.' },
    { term: 'Neuromuscular Junction', definition: 'The synapse between a motor neuron and a muscle fiber. The point where the neural signal triggers muscle contraction.', why: 'The site where the nervous system\'s recruitment signal is converted into mechanical force.' },
    { term: 'Central Nervous System Fatigue', definition: 'Reduction in the nervous system\'s ability to drive motor unit recruitment at maximum levels.', why: 'Light cardio before a maximal lift impairs CNS output without fatiguing the muscles themselves, explaining the third attempt prediction.' },
    { term: 'Synchronization', definition: 'The coordination of motor unit firing timing to maximize force output.', why: 'Elite strength athletes demonstrate higher motor unit synchronization which contributes to their ability to express near-maximal force.' },
    { term: 'Voluntary Activation', definition: 'The percentage of a muscle\'s total force capacity that the nervous system can voluntarily access. Rarely 100 percent in untrained individuals.', why: 'Explains why psychological and neural factors affect maximal strength expression independent of muscle size.' },
    { term: "Henneman's Size Principle", definition: 'Motor units are recruited from smallest to largest as force demand increases.', why: 'The foundation of understanding why light loads taken to failure eventually recruit high-threshold motor units in Branch 3.' },
    { term: 'Rate of Force Development', definition: 'How quickly a muscle can reach peak force output. Distinct from peak force itself.', why: 'The key variable distinguishing weightlifter and powerlifter performance in Branch 2 despite similar one rep max scores.' },
    { term: 'Ballistic Movement', definition: 'A movement where maximum force is applied as rapidly as possible.', why: 'The context in which rate coding differences between weightlifters and powerlifters become measurable and practically significant.' },
  ],
  4: [
    { term: 'Testosterone', definition: 'Primary anabolic sex hormone. Drives muscle protein synthesis and satellite cell activation.', why: 'The hormonal difference between the two training protocols in the root question and the central variable in the 45-year-old athlete scenario in Branch 1.' },
    { term: 'Cortisol', definition: 'Primary stress hormone. Acutely necessary for training adaptation but chronically elevated levels are catabolic.', why: 'Its dual role in Branch 2 explains why the same hormone serves different functions in resistance versus endurance training contexts.' },
    { term: 'Growth Hormone', definition: 'Anabolic hormone released during sleep and exercise. Stimulates IGF-1 production and fat mobilization.', why: 'The specific hormone whose nocturnal secretion pattern explains the sleep deprivation hypertrophy deficit in Branch 3.' },
    { term: 'Anabolic', definition: 'Promoting tissue building and muscle protein synthesis.', why: 'The hormonal environment after Athlete B\'s session is more acutely anabolic due to metabolic stress driving higher hormone release.' },
    { term: 'Catabolic', definition: 'Promoting tissue breakdown.', why: 'Chronic cortisol elevation shifts the hormonal environment toward net catabolism even when acute training responses are normal.' },
    { term: 'Hormonal Milieu', definition: 'The overall hormonal environment at a given time — the combined effect of all circulating hormones on cellular signaling.', why: 'The root question asks about this rather than any single hormone in isolation.' },
    { term: 'Metabolic Stress', definition: 'The accumulation of metabolic byproducts during high-density training.', why: 'The specific training variable driving Athlete B\'s higher hormonal response despite identical volume.' },
    { term: 'Acute Hormonal Response', definition: 'The short-term hormone elevation immediately following exercise.', why: 'The root question reveals that a larger acute response does not necessarily produce greater hypertrophy — the chronic hormonal environment matters more.' },
    { term: 'Androgen Receptor', definition: 'Cellular receptor that binds testosterone and mediates its anabolic effects.', why: 'Receptor density and sensitivity rather than hormone concentration explains why chronically low testosterone blunts hypertrophy in Branch 1.' },
    { term: 'IGF-1', definition: 'Insulin-like growth factor 1. Downstream mediator of growth hormone\'s anabolic effects.', why: 'The specific hormonal measurement that would most clearly explain the sleep deprivation hypertrophy deficit in Branch 3.' },
  ],
  5: [
    { term: 'Muscle Protein Synthesis', definition: 'The process of building new muscle proteins from amino acids.', why: 'The rate of MPS relative to muscle protein breakdown determines whether net muscle gain occurs.' },
    { term: 'Muscle Protein Breakdown', definition: 'The continuous degradation of existing muscle proteins. Always occurring simultaneously with synthesis.', why: 'Hypertrophy only happens when synthesis exceeds breakdown over time.' },
    { term: 'Net Protein Balance', definition: 'The difference between muscle protein synthesis and breakdown. Positive balance means muscle gain.', why: 'The entire root question is about what determines net protein balance across the day.' },
    { term: 'mTORC1', definition: 'Mechanistic target of rapamycin complex 1. The primary anabolic signaling hub that activates muscle protein synthesis.', why: 'The specific molecular mechanism by which protein distribution affects hypertrophy independent of total intake.' },
    { term: 'Leucine', definition: 'The essential amino acid that most powerfully activates mTORC1. Acts as a sensor for protein availability.', why: 'The mechanism by which meal protein distribution affects synthesis — each meal needs enough leucine to cross the activation threshold.' },
    { term: 'Leucine Threshold', definition: 'The minimum dose of leucine required to maximally stimulate mTORC1 and trigger a full muscle protein synthesis response.', why: 'Explains why spreading the same protein across more meals produces more synthesis opportunities than concentrating it in fewer large meals.' },
    { term: 'Anabolic Signaling', definition: 'The cascade of molecular signals from stimulus — exercise or protein — through mTORC1 to ribosomal activation and protein synthesis.', why: 'The mechanistic chain connecting training and nutrition to actual muscle growth.' },
    { term: 'Myofibrillar Hypertrophy', definition: 'Increase in the size and number of contractile myofibrils.', why: 'The type of hypertrophy most associated with strength gains and the primary target of resistance training.' },
    { term: 'Sarcoplasmic Hypertrophy', definition: 'Increase in the fluid and non-contractile proteins surrounding myofibrils.', why: 'Contributes to muscle size without proportional strength increase — relevant context for Branch 3\'s identical hypertrophy with different strength outcomes.' },
    { term: 'Protein Distribution', definition: 'The pattern of protein intake across meals throughout the day.', why: 'The central variable in the root question — same total protein distributed differently produces different synthesis outcomes through leucine threshold mechanics.' },
  ],
  6: [
    { term: 'Stroke Volume', definition: 'The volume of blood ejected by the left ventricle per heartbeat.', why: 'The structural adaptation that drives every other cardiovascular change in the root question.' },
    { term: 'Cardiac Output', definition: 'Heart rate multiplied by stroke volume. Total blood pumped per minute.', why: 'The central variable in the Fick equation determining VO2 max and the basis for calculating the pacemaker athlete\'s new performance ceiling in Branch 1.' },
    { term: 'VO2 Max', definition: 'Maximum oxygen consumption rate. The product of cardiac output and arteriovenous oxygen difference.', why: 'The performance metric whose improvement over 8 months is entirely explained by stroke volume increase and peripheral adaptations.' },
    { term: 'Eccentric Hypertrophy', definition: 'Enlargement of the heart\'s chambers through increased end-diastolic volume. The primary cardiac adaptation to endurance training.', why: 'The specific structural change that increases stroke volume and mathematically reduces resting heart rate.' },
    { term: 'End-Diastolic Volume', definition: 'The volume of blood in the ventricle just before it contracts. Increases with eccentric hypertrophy.', why: 'Directly determines stroke volume — more blood in means more blood out per beat.' },
    { term: 'Resting Heart Rate', definition: 'Heart rate at complete rest. Decreases with endurance training as a mathematical consequence of increased stroke volume.', why: 'Not an independent adaptation but a derived consequence — cardiac output at rest stays constant while stroke volume rises so heart rate must fall.' },
    { term: 'Fick Equation', definition: 'VO2 max equals cardiac output multiplied by arteriovenous oxygen difference.', why: 'The equation that allows calculation of the pacemaker athlete\'s new VO2 max and explains why peripheral adaptations matter as much as cardiac adaptations.' },
    { term: 'Arteriovenous Oxygen Difference', definition: 'The difference in oxygen content between arterial and venous blood. Reflects how much oxygen working muscles extract.', why: 'The peripheral variable that explains why the elite athlete has superior VO2 max per unit cardiac output in Branch 3.' },
    { term: 'Cardiac Adaptation', definition: 'Structural and functional changes in the heart resulting from chronic exercise training.', why: 'The mechanism connecting months of endurance training to improved exercise capacity.' },
    { term: 'Detraining', definition: 'The partial or complete reversal of training adaptations following cessation of exercise.', why: 'The root question asks specifically about the sequence and rate of detraining across three cardiovascular variables.' },
  ],
  7: [
    { term: 'Tendon', definition: 'Dense connective tissue connecting muscle to bone. Transmits contractile force to the skeleton.', why: 'The structure whose adaptation lags behind muscle and cardiovascular fitness during rapid training load increases.' },
    { term: 'Collagen', definition: 'The primary structural protein of tendons and ligaments. Type I collagen dominates tendon architecture.', why: 'Collagen synthesis rate is the rate-limiting factor in tendon adaptation and the reason connective tissue injury risk increases during rapid training load increases.' },
    { term: 'Tenocyte', definition: 'The primary cell type in tendons. Responsible for collagen synthesis and matrix remodeling in response to mechanical load.', why: 'Tenocyte mechanotransduction is the cellular mechanism of tendon adaptation and its relative slowness explains tendinopathy during rapid load increases.' },
    { term: 'Mechanotransduction', definition: 'The process by which cells convert mechanical loading into biochemical signals that drive structural adaptation.', why: 'The mechanism by which exercise produces tendon collagen synthesis and why loading frequency matters more than peak load for tendon adaptation.' },
    { term: 'Tendinopathy', definition: 'A painful degenerative condition of the tendon resulting from failed adaptation to cumulative load. Not an inflammatory condition.', why: 'The condition the runner develops in the root question and the result of training load increasing faster than tendon remodeling can keep pace.' },
    { term: 'Connective Tissue Adaptation', definition: 'Structural changes in tendons, ligaments, and fascia in response to mechanical loading.', why: 'Adapts to training load on a longer timeline than muscle or cardiovascular fitness creating a window of injury vulnerability.' },
    { term: 'Collagen Synthesis', definition: 'The production of new collagen fibers by tenocytes in response to mechanical loading.', why: 'The rate-limited process that determines how quickly tendons can adapt to increased training loads.' },
    { term: 'Remodeling', definition: 'The ongoing process of breaking down old collagen and replacing it with new collagen. Occurs continuously in tendons.', why: 'Remodeling rate determines both adaptation speed and recovery speed after injury.' },
    { term: 'Load Management', definition: 'The practice of controlling training load increase rate to match tissue adaptation capacity.', why: 'The correct intervention for the runner in the root question — not rest but controlled progressive loading within tissue tolerance.' },
    { term: 'Tissue Tolerance', definition: 'The maximum load a connective tissue can handle without structural degradation.', why: 'Exceeded tissue tolerance produces tendinopathy. Load management keeps training loads within tolerance while gradually raising the ceiling.' },
  ],
  8: [
    { term: 'Progressive Overload', definition: 'The principle that training stimulus must increase over time to continue driving adaptation.', why: 'The foundational training principle and the reason Athlete A\'s highly specific but unchanging protocol produces inferior results to Athlete B\'s varied stimulus approach.' },
    { term: 'Specificity Principle', definition: 'The principle that adaptations are specific to the demands placed on the body.', why: 'Explains why Athlete A improves at 400 meters from 400 meter training but also why excessive specificity limits overall adaptation breadth.' },
    { term: 'Adaptation', definition: 'A structural or functional change in response to a training stimulus that improves the body\'s ability to handle that stimulus in the future.', why: 'The entire purpose of training and the variable that periodization is designed to maximize.' },
    { term: 'Periodization', definition: 'The systematic variation of training variables over time to maximize adaptation while managing fatigue.', why: 'The solution to the problem of linear progressive overload becoming ineffective for advanced athletes in Branch 2.' },
    { term: 'Training Age', definition: 'How long an athlete has been training consistently.', why: 'Determines how much stimulus variation is needed for continued adaptation and how the specificity-variability tradeoff shifts as athletes approach genetic potential.' },
    { term: 'Accumulated Fatigue', definition: 'The buildup of systemic and local fatigue from training volume over time that masks true performance capacity.', why: 'The specific variable the taper in Branch 3 allows to dissipate, revealing the fitness that was built underneath it.' },
    { term: 'Detraining', definition: 'Partial reversal of training adaptations following cessation or significant reduction of training.', why: 'Branch 1 asks specifically about which adaptations are genuinely lost versus suppressed during 4 weeks of complete rest.' },
    { term: 'Supercompensation', definition: 'The temporary period after adequate recovery where performance capacity exceeds pre-training baseline.', why: 'The physiological basis of the taper effect in Branch 3 — removing accumulated fatigue allows supercompensation to express.' },
    { term: 'Taper', definition: 'A planned reduction in training volume while maintaining intensity in the period before competition or testing.', why: 'The intervention in Branch 3 that produces a 6 percent strength improvement by removing accumulated fatigue rather than adding fitness.' },
    { term: 'Stimulus Recovery Adaptation', definition: 'The three-part cycle of all training — a stimulus is applied, recovery allows adaptation, and the adaptation produces improved capacity.', why: 'The foundational model explaining why both too little and too much training produce suboptimal outcomes.' },
  ],
};

export const BRANCH_RUBRICS = {
  1: {
    branch_1: "Criterion 1: Identifies neural adaptations — motor unit recruitment and rate coding and synchronization — as the primary mechanism of strength gain without fiber type change. Criterion 2: Identifies structural adaptations — myofibrillar density and connective tissue stiffness — as secondary contributors to the power increase. Criterion 3: Correctly predicts neural adaptations reach ceiling first at approximately 8 to 12 weeks while structural adaptations continue to accrue beyond that point.",
    branch_2: "Criterion 1: Correctly predicts higher testosterone amplifies hypertrophy response more in Type II dominant muscle than Type I dominant muscle through androgen receptor density differences. Criterion 2: Identifies that the sprinter's higher Type II fiber content means more androgen receptors per unit volume available to respond to the hormonal signal. Criterion 3: Explains that the same hormonal signal produces different structural outcomes based on receptor availability not hormone concentration — the signal is the same, the responder tissue differs.",
    branch_3: "Criterion 1: Correctly explains that powerlifting's long rest periods and low rep ranges with sub-maximal sustained tension select for fatigue resistance and Type I fiber preservation rather than Type II dominance. Criterion 2: Identifies rate of force development and peak force production as distinct qualities with different fiber type dependencies — Type II for RFD, not exclusively for peak force. Criterion 3: Correctly predicts the powerlifter outperforms the sprinter on absolute peak force production but underperforms on rate of force development measured by force-time curve slope."
  },
  2: {
    branch_1: "Criterion 1: Correctly identifies lactate threshold or critical power as the metabolic variable that best explains the performance difference despite identical VO2 max values. Criterion 2: Predicts the faster athlete has a higher lactate threshold as a percentage of VO2 max — meaning they can sustain higher fractions of maximal aerobic capacity. Criterion 3: Correctly describes the faster athlete's lactate curve as shifting rightward on an intensity axis — the inflection point occurs at a higher absolute or relative workload.",
    branch_2: "Criterion 1: Correctly identifies the phosphocreatine system as dominant in the first 0 to 10 seconds and the glycolytic system as dominant from approximately 10 seconds through 300 meters, with aerobic contribution increasing in the final 100 meters. Criterion 2: Identifies hydrogen ion accumulation and inorganic phosphate accumulation — not lactate itself — as the primary metabolic drivers of neuromuscular fatigue causing the final 100 meter slowdown. Criterion 3: Assigns the slowdown to specific metabolic causation rather than motivational or volitional explanation — the athlete is not slowing down by choice.",
    branch_3: "Criterion 1: Correctly identifies improved neuromuscular power output and running economy — not aerobic capacity — as the primary mechanisms by which sprint training improves endurance performance. Criterion 2: Identifies enhanced PCr resynthesis rate or improved muscle buffering capacity as sprint-specific adaptations that transfer to reduced relative intensity during endurance effort. Criterion 3: Does not attribute the improvement to changes in VO2 max or aerobic enzyme activity — correctly frames this as a non-aerobic pathway."
  },
  3: {
    branch_1: "Criterion 1: Correctly distinguishes the upper motor neuron pathway — corticospinal tract — controlling voluntary movement from brainstem pathways controlling involuntary pattern-generated movements like yawning. Criterion 2: Correctly identifies that yawning activates a brainstem-mediated motor pattern generator that bypasses the damaged cortical pathway, which is why the muscle works involuntarily but not voluntarily. Criterion 3: Correctly predicts that motor relearning and neuroplasticity-based rehabilitation targeting cortical reorganization and voluntary pathway restoration is the most efficient rehabilitation approach.",
    branch_2: "Criterion 1: Correctly identifies rate coding — the speed at which motor units reach peak firing frequency — as the primary neuromuscular characteristic distinguishing weightlifters from powerlifters in ballistic force production tasks. Criterion 2: Explains that weightlifting-specific training with ballistic intent develops the nervous system's ability to reach peak motor unit firing frequency faster, shortening the time to peak force. Criterion 3: Predicts that weightlifting-specific training shifts the recruitment and firing curve leftward on the time axis — high-threshold units are recruited sooner and reach peak firing rate sooner.",
    branch_3: "Criterion 1: Correctly identifies fatigue-driven motor unit rotation under Henneman's size principle as the mechanism — as low-threshold units fatigue their force output drops, and the nervous system recruits progressively higher-threshold units to maintain total force. Criterion 2: Correctly predicts that proximity to failure equates the hypertrophic stimulus between low-load-to-failure and high-load-stopped-short-of-failure protocols because high-threshold motor unit recruitment is the common mechanism in both. Criterion 3: Does not attribute high-threshold motor unit recruitment at low loads to the load magnitude itself — correctly frames it as a fatigue-driven recruitment escalation."
  },
  4: {
    branch_1: "Criterion 1: Correctly identifies that chronic low resting testosterone creates a suboptimal androgenic baseline between training sessions — not just during acute response — meaning the inter-session anabolic environment is persistently compromised. Criterion 2: Identifies androgen receptor downregulation or downstream signaling cascade impairment — specifically reduced mTORC1 activation amplitude — as the point where the deficit manifests rather than at the hormone secretion step. Criterion 3: Does not attribute the blunted hypertrophy solely to blunted acute hormonal response magnitude — correctly identifies the problem as chronic baseline deficiency affecting the 23-plus hours between sessions.",
    branch_2: "Criterion 1: Correctly identifies cortisol's primary role during endurance training as substrate mobilization — liberating glucose and fatty acids for sustained energy provision rather than tissue remodeling. Criterion 2: Correctly identifies that chronically elevated resting cortisol creates a net catabolic state by chronically elevating muscle protein breakdown rate, tipping the protein balance negative outside of training windows. Criterion 3: Correctly explains that the temporal relationship between cortisol and anabolic hormones determines net protein balance — acute cortisol during training followed by anabolic recovery is adaptive; chronically elevated baseline cortisol without adequate anabolic counterbalance is catabolic.",
    branch_3: "Criterion 1: Correctly identifies overnight growth hormone secretion during deep sleep as the specific recovery window where the hormonal divergence between athletes is greatest — the sleep-deprived athlete loses the primary nocturnal GH pulse. Criterion 2: Identifies IGF-1 as the downstream mediator of growth hormone's anabolic effect on muscle protein synthesis, linking the GH deficit to reduced local anabolic signaling. Criterion 3: Predicts nocturnal growth hormone area under the curve — the total GH secreted during sleep — as the single measurement that would most clearly differentiate the two athletes' recovery environments."
  },
  5: {
    branch_1: "Criterion 1: Correctly identifies the cross-education effect operating through shared neural pathways — bilateral cortical activation during unilateral training sends some neural drive to the contralateral limb — as a mechanism attenuating atrophy in the immobilized arm. Criterion 2: Identifies systemic anabolic hormonal environment — elevated IGF-1 and testosterone from intensive unilateral training — as a second contributing pathway providing partial systemic anabolic signal to the immobilized muscle. Criterion 3: Correctly predicts that the cross-education effect is meaningful enough to meaningfully reduce atrophy rate but insufficient to maintain full strength without direct training stimulus to that limb.",
    branch_2: "Criterion 1: Correctly identifies that resistance exercise activates mTORC1 through a mechanical tension pathway — mechanotransduction via Akt and upstream sensors — while leucine activates mTORC1 through a distinct amino acid sensing pathway via Ragulator-Rag complex, and these are genuinely separate upstream inputs converging on mTORC1. Criterion 2: Correctly predicts that combining both stimuli produces supraadditive mTORC1 activation because both upstream pathways converge simultaneously, amplifying downstream signaling beyond either alone. Criterion 3: Correctly identifies that the timing effect diminishes in highly trained individuals because chronic training elevates baseline mTORC1 sensitivity throughout the day, compressing the window advantage that beginners experience.",
    branch_3: "Criterion 1: Correctly identifies mechanical tension and metabolic stress as the shared drivers of hypertrophic stimulus in both programs — not load magnitude specifically — explaining why identical hypertrophy is possible through mechanically different loading approaches. Criterion 2: Correctly explains that Program A produces superior strength gains because progressive load increase specifically adapts the nervous system and connective tissue to heavier absolute loads, an adaptation Program B does not provide. Criterion 3: Does not attribute identical hypertrophy to identical load schemes — correctly identifies that the actual driver is the mechanical and metabolic stimulus reaching muscle fibers regardless of the specific loading strategy."
  },
  6: {
    branch_1: "Criterion 1: Correctly applies the Fick equation — VO2 max equals cardiac output multiplied by arteriovenous oxygen difference — to calculate the new VO2 max given the fixed maximum heart rate constraint of 70 bpm and the known stroke volume, arriving at a substantially reduced value. Criterion 2: Correctly identifies that arteriovenous oxygen difference becomes the most limiting component given cardiac output is now severely constrained by the fixed heart rate ceiling. Criterion 3: Correctly predicts that sprint and short middle distance performance are most severely impacted because they depend most heavily on maximal cardiac output, while ultra-endurance events operating at lower fractions of maximum are comparatively less impacted.",
    branch_2: "Criterion 1: Correctly identifies eccentric hypertrophy in endurance athletes — increased chamber volume from volume overload — and concentric hypertrophy in strength athletes — increased wall thickness from pressure overload — as mechanistically opposite cardiac responses to different mechanical demands. Criterion 2: Correctly predicts that a concurrent training athlete develops an intermediate cardiac phenotype with both increased chamber volume and moderate wall thickening rather than one or the other. Criterion 3: Correctly identifies the combined phenotype as advantageous because it provides both high stroke volume from large chamber size and adequate ejection pressure from moderately thickened walls — each modality's cardiac adaptation is additive not competitive.",
    branch_3: "Criterion 1: Correctly identifies peripheral oxygen extraction — the arteriovenous oxygen difference — as the variable explaining why the older trained individual requires more cardiac output per unit of oxygen consumed. Criterion 2: Correctly identifies mitochondrial density, capillary density, and oxidative enzyme activity as the peripheral adaptations responsible for the elite athlete's superior oxygen extraction per unit of blood flow. Criterion 3: Correctly frames the older trained individual's higher cardiac output requirement as reflecting less efficient peripheral oxygen extraction — the heart must pump more blood to deliver the same amount of oxygen to working muscle."
  },
  7: {
    branch_1: "Criterion 1: Correctly identifies higher baseline collagen fibril diameter, collagen density, and greater cross-link maturity in Athlete A's pre-injury ligament as the structural differences produced by years of training — a more robust collagen matrix. Criterion 2: Correctly identifies mechanotransduction through ligamentocyte fibroblast activity as the cellular mechanism — repeated mechanical loading stimulates fibroblasts to produce and organize more and better-quality collagen over training years. Criterion 3: Correctly predicts that the recovered ligament does not fully return to pre-injury structural quality — scar tissue collagen has inferior fiber organization and cross-linking compared to native ligament collagen, even with excellent rehabilitation.",
    branch_2: "Criterion 1: Correctly identifies that stiffer tendons transmit force from muscle to bone more rapidly by reducing the elastic lag — the brief delay while slack tendon takes up before force is transmitted — thereby reducing electromechanical delay. Criterion 2: Correctly identifies rate of force development enhancement — the slope of the force-time curve — as the specific mechanical advantage of tendon stiffness rather than an increase in peak force capacity itself. Criterion 3: Correctly predicts that an athlete with high muscular strength but undertrained tendon stiffness will show a delayed and blunted force-time curve — they eventually produce high force but the rate at which force rises is compromised.",
    branch_3: "Criterion 1: Correctly identifies cyclical loading frequency — the total number of loading cycles — rather than peak force magnitude as the primary driver of tendon collagen synthesis rate. Criterion 2: Correctly identifies that moderate cyclical loading activates tenocyte mechanotransduction more consistently and repeatedly than infrequent high-load events — the accumulated mechanical stimulus over many cycles outweighs intermittent high peaks. Criterion 3: Correctly predicts an optimal return-to-sport tendon conditioning protocol that prioritizes high-repetition moderate-load exercises before progressing to high-load low-repetition work — building collagen synthesis capacity before imposing peak force demands."
  },
  8: {
    branch_1: "Criterion 1: Correctly identifies that neuromuscular adaptations — motor pattern efficiency, calcium handling — and biochemical adaptations — enzyme activity, plasma volume — are suppressed or reduced rather than structurally lost during 4 weeks, enabling rapid restoration once training resumes. Criterion 2: Correctly distinguishes genuinely lost adaptations — such as partial capillary regression and some mitochondrial density reduction — from suppressed or downregulated adaptations that restore faster, explaining why restoration in 3 weeks is possible but not all adaptations recover equally fast. Criterion 3: Correctly predicts that 6-month detraining produces genuine structural regression — significant myonuclear loss, capillary regression, and connective tissue remodeling — requiring a full adaptation timeline to restore, not the rapid 3-week restoration seen after 4 weeks.",
    branch_2: "Criterion 1: Correctly identifies that accumulated fatigue — central nervous system fatigue, connective tissue microtrauma, and hormonal suppression from sustained high volume — masks true strength capacity during the high-volume training phase, making performance appear plateaued when underlying fitness is still improving. Criterion 2: Correctly identifies that maintaining training intensity during a taper preserves the neural drive and fitness signal while the reduction in volume allows the accumulated fatigue to dissipate, unmasking the fitness that was hidden underneath. Criterion 3: Correctly predicts that optimal taper parameters are approximately 2 to 3 weeks duration with 40 to 60 percent volume reduction while keeping intensity at or above pre-taper levels — enough to clear fatigue without allowing significant detraining.",
    branch_3: "Criterion 1: Correctly identifies fatigue dissipation as the primary physiological mechanism of the performance increase — the taper removes accumulated fatigue that was suppressing neuromuscular expression of true fitness. Criterion 2: Correctly distinguishes fitness and fatigue as separate variables that both accumulate during high-volume training — fitness builds slowly, fatigue accumulates faster, and the taper selectively removes fatigue while preserving fitness. Criterion 3: Correctly predicts optimal taper parameters of 2 to 3 weeks duration and approximately 40 to 60 percent volume reduction while maintaining intensity, and identifies that tapers shorter than 2 weeks or longer than 3 weeks are suboptimal for different reasons."
  }
};