export const ROOTS = [
  {
    id: 1,
    title: "Muscle Fiber Architecture and Force Production",
    rootQuestion: `A sprinter and a marathon runner have identical total quadriceps muscle volume confirmed by MRI. During a maximal sprint the sprinter produces 340 watts of peak power. The marathon runner produces 180 watts peak power from the same muscle volume. Neither athlete is injured. Explain the specific structural difference in muscle fiber composition that accounts for this power differential, explain why fiber type produces this difference mechanistically rather than just correlating with it, and predict what would happen to each athlete's power output and fatigue rate if both performed a 45-minute moderate intensity cycling session immediately before the sprint test.`,
    branches: [
      {
        label: "Edge Case",
        question: `A previously sedentary person begins a 16-week resistance training program. Muscle biopsies taken before and after show no significant change in the ratio of Type I to Type II fibers. Yet their peak power output has increased by 35 percent. Explain the specific structural and neural adaptations that produced this power increase without fiber type conversion, and predict which of these adaptations reached its ceiling first.`
      },
      {
        label: "Cross-Root Integration",
        question: `The sprinter from the root question also has a significantly higher testosterone response to resistance training than the marathon runner. Using your understanding of both muscle fiber architecture and hormonal response to exercise, predict how the hormonal difference interacts with the existing fiber type composition to affect hypertrophy potential in each athlete, and explain why the same hormonal signal produces different structural outcomes in fiber-type-different muscles.`
      },
      {
        label: "Counterintuitive Prediction",
        question: `A muscle biopsy of an elite powerlifter shows that 60 percent of their vastus lateralis fibers are Type I slow-twitch despite their sport demanding maximal force production. Explain why this finding is less surprising than it initially appears, identify the specific training characteristic of powerlifting that selects for this fiber composition, and predict how this powerlifter's performance would compare to a sprinter on a test of maximal force production versus rate of force development.`
      }
    ],
    rubric: "Identifies Type I vs Type II fiber distinction as the mechanism. Connects fiber type to contractile speed and fatigue resistance mechanistically not just definitionally. Predicts pre-fatigue effect on both athletes using fiber type logic. Addresses power differential as structural not motivational."
  },
  {
    id: 2,
    title: "Energy Systems and Their Interaction",
    rootQuestion: `A cyclist is performing a 20-minute time trial at maximum sustainable effort. At the 30-second mark their power output is 420 watts. At the 5-minute mark it has dropped to 310 watts. At the 15-minute mark it has stabilized at 285 watts. They are not pacing — they are going as hard as possible at each moment. Explain the specific energy system transitions that account for this power output curve, identify the metabolic event that causes the drop from 420 to 310 watts specifically, and predict what the power output curve would look like if the same athlete performed the same test after 3 days of carbohydrate restriction to deplete muscle glycogen.`,
    branches: [
      {
        label: "Edge Case",
        question: `Two athletes have identical VO2 max values of 65 ml/kg/min. In a 10km race one athlete runs 32 minutes and the other runs 38 minutes. Using energy system principles explain what specific metabolic variable best explains this performance difference despite identical maximal aerobic capacity, and predict how each athlete's lactate curve would look during an incremental exercise test.`
      },
      {
        label: "Cross-Root Integration",
        question: `The phosphocreatine system and the glycolytic system both contribute to a 400-meter sprint. Using your understanding of energy systems and muscle fiber architecture predict how the relative contribution of each system changes across the 400 meters, explain why the dramatic slowdown in the final 100 meters of most 400-meter races is a metabolic event not a motivational one, and identify the specific metabolic accumulation that drives this slowdown.`
      },
      {
        label: "Counterintuitive Prediction",
        question: `An endurance athlete performs 8 weeks of sprint interval training — 6 second maximal sprints with 4 minute recovery — with no changes to their steady-state aerobic training. Their 10km race time improves by 90 seconds despite the interval training never stressing their aerobic system significantly. Explain the specific adaptations from sprint interval training that improve endurance performance through a non-aerobic mechanism.`
      }
    ],
    rubric: "Correctly identifies the three energy system transitions across the time trial. Identifies PCr depletion as the specific mechanism for the early power drop. Predicts glycogen depletion effects on both the aerobic and anaerobic contributions correctly."
  },
  {
    id: 3,
    title: "Neuromuscular Activation and Motor Unit Recruitment",
    rootQuestion: `A powerlifter attempts a maximal deadlift of 250kg — a weight they have lifted before. On the first attempt they fail at the sticking point. On the second attempt 4 minutes later they successfully complete the lift. Their muscle strength has not changed between attempts. Explain the specific neuromuscular mechanism that allowed the second attempt to succeed where the first failed, identify what changed in the nervous system between attempts rather than in the muscle, and predict what would happen to their maximal lift capacity if they performed 30 minutes of light cardio immediately before the third attempt.`,
    branches: [
      {
        label: "Edge Case",
        question: `A stroke patient has lost the ability to voluntarily activate the left bicep despite the muscle being completely intact — no atrophy, normal histology, normal response to direct electrical stimulation. Yet when the patient yawns, the left bicep contracts involuntarily. Explain the specific neurological distinction between voluntary and involuntary motor activation that accounts for this pattern, and predict what rehabilitation approach would most efficiently restore voluntary control.`
      },
      {
        label: "Cross-Root Integration",
        question: `Elite weightlifters produce higher peak forces than equally strong powerlifters during ballistic movements despite having similar one-rep max scores. Using your understanding of both motor unit recruitment and muscle fiber architecture explain the specific neuromuscular characteristic that accounts for this difference in rate of force development, and predict how training each quality specifically changes the recruitment pattern over time.`
      },
      {
        label: "Counterintuitive Prediction",
        question: `A researcher measures motor unit recruitment during a set of bicep curls taken to failure with a light weight — 30 percent of one rep max. Early in the set only low-threshold motor units are active. By the final repetitions before failure, high-threshold motor units are fully recruited despite the load being only 30 percent of maximum. Explain the specific mechanism that forces high-threshold motor unit recruitment at low loads when taken to failure, and predict the hypertrophy stimulus of this protocol compared to a heavy set at 85 percent of one rep max stopped well short of failure.`
      }
    ],
    rubric: "Identifies rate coding and motor unit synchronization as what changed between attempts not muscle strength. Addresses the post-activation potentiation mechanism. Predicts cardio effect using the mechanism of neural fatigue rather than muscular fatigue."
  },
  {
    id: 4,
    title: "Acute Hormonal Response to Training",
    rootQuestion: `Two athletes perform resistance training sessions of identical volume — same exercises, sets, reps, and total tonnage. Athlete A performs the session as straight sets with 3 minutes rest between sets over 60 minutes. Athlete B performs the same volume as supersets with 60 seconds rest between exercises over 35 minutes. Blood samples taken immediately after each session show dramatically different hormonal profiles — Athlete B has significantly higher testosterone, growth hormone, and cortisol. Both athletes have trained for 5 years. Explain the specific training variable that drives the hormonal difference, predict whether the higher hormonal response in Athlete B produces greater muscle protein synthesis over the following 48 hours, and explain why the answer to that prediction is less straightforward than it initially appears.`,
    branches: [
      {
        label: "Edge Case",
        question: `A 45-year-old male athlete has resting testosterone levels 40 percent below the normal range for his age despite excellent health, nutrition, and sleep. His resistance training produces a normal acute hormonal response — testosterone rises appropriately during and after training. Yet his hypertrophy response to training over 12 weeks is significantly blunted compared to age-matched peers with normal testosterone. Explain the specific mechanism by which chronically low resting testosterone blunts hypertrophy despite normal acute response, and identify at what point in the muscle protein synthesis cascade the deficit manifests.`
      },
      {
        label: "Cross-Root Integration",
        question: `Cortisol rises acutely during both resistance training and endurance training. Using your understanding of hormonal response and energy systems explain why acute cortisol elevation during training serves a different metabolic function in resistance versus endurance contexts, predict the consequence of chronically elevated resting cortisol on muscle protein balance, and explain why the timing of cortisol elevation relative to anabolic hormones determines whether the net effect is catabolic or anabolic.`
      },
      {
        label: "Counterintuitive Prediction",
        question: `Two athletes have identical training programs and nutrition. Athlete A sleeps 8 hours per night consistently. Athlete B sleeps 5.5 hours per night. After 12 weeks Athlete B has gained significantly less muscle despite identical training stimulus and caloric intake. A muscle biopsy shows identical rates of muscle protein synthesis in both athletes measured immediately after training sessions. Explain where in the 24-hour recovery cycle the hormonal difference between athletes is producing the divergent outcomes, and predict the specific hormonal measurement that would most clearly explain the difference.`
      }
    ],
    rubric: "Identifies metabolic stress and hormonal milieu as the driver of hormonal difference. Addresses the distinction between acute hormonal spike and chronic anabolic environment. Predicts sleep deprivation effect at the hormonal synthesis level not just the training level."
  },
  {
    id: 5,
    title: "Muscle Protein Synthesis and the Hypertrophy Signal",
    rootQuestion: `A researcher gives two groups of subjects identical resistance training programs for 16 weeks. Group A consumes 1.6 grams of protein per kilogram of bodyweight daily evenly distributed across 4 meals. Group B consumes the same total daily protein in 2 meals — a small breakfast and a large dinner. Both groups gain strength equally. Group A gains significantly more muscle mass. Explain the specific molecular mechanism by which protein distribution affects muscle protein synthesis independent of total protein intake, identify the signaling pathway that is differentially activated, and predict the minimum meal protein dose required to maximally stimulate this pathway in a trained individual versus an untrained individual.`,
    branches: [
      {
        label: "Edge Case",
        question: `A bodybuilder tears their left bicep completely at the musculotendinous junction and undergoes surgical repair. During the 12-week immobilization period they continue training the right arm intensively. At 12 weeks the right arm has gained 2cm of circumference. Surprisingly the left arm, while atrophied, has lost less muscle than predicted by immobilization research. Explain the specific mechanism by which intensive unilateral training attenuates contralateral muscle atrophy, identify the neural and systemic pathways responsible, and predict whether this cross-education effect is sufficient to meaningfully affect rehabilitation outcomes.`
      },
      {
        label: "Cross-Root Integration",
        question: `mTORC1 is the primary anabolic signaling hub for muscle protein synthesis. Both resistance exercise and leucine from dietary protein activate mTORC1. Using your understanding of muscle protein synthesis and hormonal response to training explain why combining resistance exercise and protein intake produces greater mTORC1 activation than either stimulus alone, predict the optimal timing window between training and protein intake for maximal synergistic activation, and explain why this timing effect diminishes in highly trained individuals compared to beginners.`
      },
      {
        label: "Counterintuitive Prediction",
        question: `A study compares two hypertrophy programs over 6 months. Program A uses traditional progressive overload — adding weight each week. Program B keeps weight constant but increases reps until a set becomes easy then adds a small weight increment. Both programs equate total volume. At 6 months muscle biopsies show identical hypertrophy. However subjects in Program B report significantly lower perceived exertion and better recovery. Explain why identical hypertrophy outcomes are possible through mechanically different loading approaches, identify what the actual driver of the hypertrophic stimulus is in both programs, and predict which program would produce greater strength gains despite identical hypertrophy.`
      }
    ],
    rubric: "Identifies leucine threshold and mTORC1 activation as the mechanism. Connects protein distribution to pulsatile mTORC1 activation versus sustained low-level activation. Addresses the trained versus untrained leucine threshold difference."
  },
  {
    id: 6,
    title: "Cardiovascular Adaptation to Endurance Training",
    rootQuestion: `An untrained 25-year-old begins an 8-month endurance training program. At baseline their resting heart rate is 72 bpm, stroke volume is 70ml, and VO2 max is 38 ml/kg/min. After 8 months their resting heart rate is 48 bpm, stroke volume is 105ml, and VO2 max is 52 ml/kg/min. Their maximum heart rate has not changed. Explain the specific structural cardiac adaptation that accounts for the stroke volume increase, explain why resting heart rate decreases as a mathematical consequence of stroke volume increase rather than as an independent adaptation, and predict what happens to each of these three variables during the first 3 weeks of complete detraining.`,
    branches: [
      {
        label: "Edge Case",
        question: `A competitive cyclist with a VO2 max of 72 ml/kg/min and resting heart rate of 38 bpm develops a cardiac arrhythmia requiring a pacemaker set at a fixed rate of 70 bpm. Their maximum achievable heart rate is now 70 bpm — well below the normal maximum. Predict their new VO2 max and explain the specific cardiovascular equation that determines this value, identify which component of the Fick equation is most limiting in this scenario, and predict how this athlete's performance across different event durations — sprint versus middle distance versus ultra-endurance — changes relative to their pre-pacemaker capacity.`
      },
      {
        label: "Cross-Root Integration",
        question: `Endurance training and resistance training produce opposing cardiac adaptations — eccentric versus concentric hypertrophy. Using your understanding of cardiovascular adaptation and the energy systems explain why the mechanical demand of each training modality produces structurally opposite cardiac responses, predict the cardiac morphology of an athlete who trains both modalities equally at high volume, and explain why the combined cardiac phenotype is actually advantageous rather than a compromise.`
      },
      {
        label: "Counterintuitive Prediction",
        question: `A 50-year-old sedentary individual begins endurance training and after one year achieves a VO2 max of 45 ml/kg/min — above average for their age. An elite 20-year-old endurance athlete has a VO2 max of 78 ml/kg/min. The older trained individual's cardiac output at maximal exercise is actually higher relative to their VO2 max than the elite athlete's. Explain the specific cardiovascular variable that accounts for this — why the older trained individual needs more cardiac output per unit of oxygen consumed than the elite athlete — and predict what peripheral adaptation in the elite athlete explains their superior oxygen extraction efficiency.`
      }
    ],
    rubric: "Identifies eccentric cardiac hypertrophy and increased end-diastolic volume as the structural basis of stroke volume increase. Derives resting heart rate decrease mathematically from stroke volume increase using the cardiac output equation. Predicts detraining sequence correctly — stroke volume reverses faster than VO2 max."
  },
  {
    id: 7,
    title: "Connective Tissue Adaptation",
    rootQuestion: `A 28-year-old recreational runner increases their weekly mileage from 30km to 60km over 6 weeks in preparation for a marathon. At week 5 they develop Achilles tendinopathy — pain and morning stiffness at the Achilles tendon insertion. Their cardiovascular fitness has improved normally throughout this period. The tendon has not ruptured. Explain the specific structural reason why connective tissue adaptation lags behind cardiovascular and muscular adaptation during rapid training load increases, identify the cellular mechanism responsible for tendon remodeling and why it is rate-limited, and predict what training modification would allow this athlete to reach 60km per week without developing tendinopathy given a longer timeline.`,
    branches: [
      {
        label: "Edge Case",
        question: `Two athletes sustain identical grade 2 medial collateral ligament sprains of the knee. Athlete A has been resistance training for 6 years. Athlete B has been sedentary. MRI confirms equivalent ligament damage in both. At 12 weeks Athlete A has returned to full sport while Athlete B is still in rehabilitation. Both athletes had identical rehabilitation programs. Explain the specific pre-injury structural differences in Athlete A's ligament that account for the faster recovery, identify the cellular mechanism that produced these structural differences through training, and predict whether the recovered ligament in Athlete A returns to its pre-injury structural quality.`
      },
      {
        label: "Cross-Root Integration",
        question: `Heavy resistance training produces both muscular hypertrophy and increased tendon stiffness. Using your understanding of connective tissue adaptation and neuromuscular activation explain why increased tendon stiffness is actually advantageous for force production rather than simply being a parallel adaptation, identify the specific mechanical property of stiff tendons that enhances rate of force development, and predict the performance consequence for an athlete who has high muscular strength but undertrained tendon stiffness.`
      },
      {
        label: "Counterintuitive Prediction",
        question: `A researcher compares tendon collagen synthesis rates in athletes performing heavy resistance training versus moderate intensity endurance training matched for total lower limb mechanical loading. The endurance training group shows higher rates of tendon collagen synthesis despite lower peak forces. Explain the specific loading characteristic — not peak force — that most strongly drives tendon collagen synthesis, identify what property of cyclical loading at moderate force is a stronger collagen synthesis stimulus than infrequent loading at high force, and predict the optimal tendon conditioning protocol for an athlete returning from tendon injury.`
      }
    ],
    rubric: "Identifies tenocyte remodeling rate as the rate-limiting factor. Explains the vascularity deficit of tendon compared to muscle as the mechanistic basis of slower adaptation. Predicts the correct training modification using load management principles not rest."
  },
  {
    id: 8,
    title: "Training Principles: Overload, Specificity, and Recovery",
    rootQuestion: `Two athletes both want to improve their 400-meter sprint time. Athlete A runs 400-meter repeats at race pace 4 times per week. Athlete B runs a variety of distances — 100m, 200m, 400m, and 800m repeats — at varied intensities 5 times per week with one session per week of heavy resistance training. After 16 weeks Athlete A has improved their 400m time by 1.8 seconds. Athlete B has improved by 3.1 seconds. Both athletes recovered well with no injuries. Explain the specific training principle that accounts for Athlete B's superior improvement despite less specific training, predict which athlete has a higher ceiling for further improvement at the 400-meter distance, and explain why the optimal specificity ratio changes as an athlete approaches their genetic potential.`,
    branches: [
      {
        label: "Edge Case",
        question: `A highly trained athlete takes a planned 4-week complete rest period — no training whatsoever. At the end of 4 weeks their VO2 max has dropped by 8 percent, their strength has dropped by 4 percent, and their body composition has changed minimally. They resume training and within 3 weeks are back to all baseline measures. Explain the specific mechanisms that allow such rapid restoration of fitness, identify what structural adaptations are genuinely lost versus simply suppressed during detraining, and predict how the detraining and retraining response would differ for an athlete who takes a 6-month break rather than 4 weeks.`
      },
      {
        label: "Cross-Root Integration",
        question: `Progressive overload requires continually increasing training stress to drive adaptation. Using your understanding of both training principles and hormonal response explain why linear progressive overload — adding weight every session — works well for beginners but produces diminishing returns and increasing injury risk for advanced athletes, identify the specific hormonal and structural reason the adaptation curve flattens, and predict the optimal periodization structure for an advanced athlete that maintains progressive overload without requiring linear load increases every session.`
      },
      {
        label: "Counterintuitive Prediction",
        question: `A strength athlete reduces their training volume by 40 percent for 3 weeks while maintaining training intensity — same weights, fewer sets. At the end of the taper their performance on a maximal strength test improves by 6 percent compared to their pre-taper baseline. Explain the specific physiological mechanism by which reducing training volume while maintaining intensity produces a performance increase rather than a decrease, identify what was accumulating during the high-volume training phase that was masking true strength capacity, and predict the optimal taper duration and volume reduction percentage for maximizing this effect.`
      }
    ],
    rubric: "Identifies concurrent training and varied stimulus as the mechanism behind Athlete B's superior improvement through the principle of varied adaptation stimulus. Addresses the specificity-variability tradeoff and how it shifts with training age. Predicts taper effect through the accumulated fatigue masking fitness concept."
  }
];

export const BRANCH_RUBRICS = {
  1: {
    branch_1: "Criterion 1: Identifies neural adaptations — motor unit recruitment and rate coding and synchronization — as the primary mechanism of strength gain without fiber type change. Criterion 2: Identifies structural adaptations — myofibrillar density and connective tissue stiffness — as secondary contributors to the power increase. Criterion 3: Correctly predicts neural adaptations reach ceiling first at approximately 8 to 12 weeks while structural adaptations continue to accrue beyond that point.",
    branch_2: "Criterion 1: Correctly predicts higher testosterone amplifies hypertrophy response more in Type II dominant muscle than Type I dominant muscle through androgen receptor density differences. Criterion 2: Identifies that the sprinter's higher Type II fiber content means more androgen receptors per unit volume available to respond to the hormonal signal. Criterion 3: Explains that the same hormonal signal produces different structural outcomes based on receptor availability not hormone concentration — the signal is the same, the responder tissue differs.",
    branch_3: "Criterion 1: Correctly explains that powerlifting's long rest periods and low rep ranges with sub-maximal sustained tension select for fatigue resistance and Type I fiber preservation rather than Type II dominance. Criterion 2: Identifies rate of force development and peak force production as distinct qualities with different fiber type dependencies — Type II for RFD, not exclusively for peak force. Criterion 3: Correctly predicts the powerlifter outperforms the sprinter on absolute peak force production but underperforms on rate of force development measured by force-time curve slope."
  },
  2: {
    branch_1: "Criterion 1: Correctly identifies lactate threshold or critical power as the metabolic variable that best explains the performance difference despite identical VO2 max values. Criterion 2: Predicts the faster athlete has a higher lactate threshold as a percentage of VO2 max — meaning they can sustain higher fractions of maximal aerobic capacity. Criterion 3: Correctly describes the faster athlete's lactate curve as shifting rightward on an intensity axis — the inflection point occurs at a higher absolute or relative workload.",
    branch_2: "Criterion 1: Correctly identifies the phosphocreatine system as dominant in the first 0 to 10 seconds and the glycolytic system as dominant from approximately 10 seconds through 300 meters, with aerobic contribution increasing in the final 100 meters. Criterion 2: Identifies hydrogen ion accumulation and inorganic phosphate accumulation — not lactate itself — as the primary metabolic drivers of neuromuscular fatigue causing the final 100 meter slowdown. Criterion 3: Assigns the slowdown to specific metabolic causation rather than motivational or volitional explanation — the athlete is not slowing down by choice.",
    branch_3: "Criterion 1: Correctly identifies improved neuromuscular power output and running economy — not aerobic capacity — as the primary mechanisms by which sprint training improves endurance performance. Criterion 2: Identifies enhanced PCr resynthesis rate or improved muscle buffering capacity as sprint-specific adaptations that transfer to reduced relative intensity during endurance effort. Criterion 3: Does not attribute the improvement to changes in VO2 max or aerobic enzyme activity — correctly frames this as a non-aerobic pathway."
  },
  3: {
    branch_1: "Criterion 1: Correctly distinguishes the upper motor neuron pathway — corticospinal tract — controlling voluntary movement from brainstem pathways controlling involuntary pattern-generated movements like yawning. Criterion 2: Correctly identifies that yawning activates a brainstem-mediated motor pattern generator that bypasses the damaged cortical pathway, which is why the muscle works involuntarily but not voluntarily. Criterion 3: Correctly predicts that motor relearning and neuroplasticity-based rehabilitation targeting cortical reorganization and voluntary pathway restoration is the most efficient rehabilitation approach.",
    branch_2: "Criterion 1: Correctly identifies rate coding — the speed at which motor units reach peak firing frequency — as the primary neuromuscular characteristic distinguishing weightlifters from powerlifters in ballistic force production tasks. Criterion 2: Explains that weightlifting-specific training with ballistic intent develops the nervous system's ability to reach peak motor unit firing frequency faster, shortening the time to peak force. Criterion 3: Predicts that weightlifting-specific training shifts the recruitment and firing curve leftward on the time axis — high-threshold units are recruited sooner and reach peak firing rate sooner.",
    branch_3: "Criterion 1: Correctly identifies fatigue-driven motor unit rotation under Henneman's size principle as the mechanism — as low-threshold units fatigue their force output drops, and the nervous system recruits progressively higher-threshold units to maintain total force. Criterion 2: Correctly predicts that proximity to failure equates the hypertrophic stimulus between low-load-to-failure and high-load-stopped-short-of-failure protocols because high-threshold motor unit recruitment is the common mechanism in both. Criterion 3: Does not attribute high-threshold motor unit recruitment at low loads to the load magnitude itself — correctly frames it as a fatigue-driven recruitment escalation."
  },
  4: {
    branch_1: "Criterion 1: Correctly identifies that chronic low resting testosterone creates a suboptimal androgenic baseline between training sessions — not just during acute response — meaning the inter-session anabolic environment is persistently compromised. Criterion 2: Identifies androgen receptor downregulation or downstream signaling cascade impairment — specifically reduced mTORC1 activation amplitude — as the point where the deficit manifests rather than at the hormone secretion step. Criterion 3: Does not attribute the blunted hypertrophy solely to blunted acute hormonal response magnitude — correctly identifies the problem as chronic baseline deficiency affecting the 23-plus hours between sessions.",
    branch_2: "Criterion 1: Correctly identifies cortisol's primary role during endurance training as substrate mobilization — liberating glucose and fatty acids for sustained energy provision rather than tissue remodeling. Criterion 2: Correctly identifies that chronically elevated resting cortisol creates a net catabolic state by chronically elevating muscle protein breakdown rate, tipping the protein balance negative outside of training windows. Criterion 3: Correctly explains that the temporal relationship between cortisol and anabolic hormones determines net protein balance — acute cortisol during training followed by anabolic recovery is adaptive; chronically elevated baseline cortisol without adequate anabolic counterbalance is catabolic.",
    branch_3: "Criterion 1: Correctly identifies overnight growth hormone secretion during deep sleep as the specific recovery window where the hormonal divergence between athletes is greatest — the sleep-deprived athlete loses the primary nocturnal GH pulse. Criterion 2: Identifies IGF-1 as the downstream mediator of growth hormone's anabolic effect on muscle protein synthesis, linking the GH deficit to reduced local anabolic signaling. Criterion 3: Predicts nocturnal growth hormone area under the curve — the total GH secreted during sleep — as the single measurement that would most clearly differentiate the two athletes' recovery environments."
  },
  5: {
    branch_1: "Criterion 1: Correctly identifies the cross-education effect operating through shared neural pathways — bilateral cortical activation during unilateral training sends some neural drive to the contralateral limb — as a mechanism attenuating atrophy in the immobilized arm. Criterion 2: Identifies systemic anabolic hormonal environment — elevated IGF-1 and testosterone from intensive unilateral training — as a second contributing pathway providing partial systemic anabolic signal to the immobilized muscle. Criterion 3: Correctly predicts that the cross-education effect is meaningful enough to meaningfully reduce atrophy rate but insufficient to maintain full strength without direct training stimulus to that limb.",
    branch_2: "Criterion 1: Correctly identifies that resistance exercise activates mTORC1 through a mechanical tension pathway — mechanotransduction via Akt and upstream sensors — while leucine activates mTORC1 through a distinct amino acid sensing pathway via Ragulator-Rag complex, and these are genuinely separate upstream inputs converging on mTORC1. Criterion 2: Correctly predicts that combining both stimuli produces supraadditive mTORC1 activation because both upstream pathways converge simultaneously, amplifying downstream signaling beyond either alone. Criterion 3: Correctly identifies that the timing effect diminishes in highly trained individuals because chronic training elevates baseline mTORC1 sensitivity throughout the day, compressing the window advantage that beginners experience.",
    branch_3: "Criterion 1: Correctly identifies mechanical tension and metabolic stress as the shared drivers of hypertrophic stimulus in both programs — not load magnitude specifically — explaining why identical hypertrophy is possible through mechanically different loading approaches. Criterion 2: Correctly explains that Program A produces superior strength gains because progressive load increase specifically adapts the nervous system and connective tissue to heavier absolute loads, an adaptation Program B does not provide. Criterion 3: Does not attribute identical hypertrophy to identical load schemes — correctly identifies that the actual driver is the mechanical and metabolic stimulus reaching muscle fibers regardless of the specific loading strategy."
  },
  6: {
    branch_1: "Criterion 1: Correctly applies the Fick equation — VO2 max equals cardiac output multiplied by arteriovenous oxygen difference — to calculate the new VO2 max given the fixed maximum heart rate constraint of 70 bpm and the known stroke volume, arriving at a substantially reduced value. Criterion 2: Correctly identifies that arteriovenous oxygen difference becomes the most limiting component given cardiac output is now severely constrained by the fixed heart rate ceiling. Criterion 3: Correctly predicts that sprint and short middle distance performance are most severely impacted because they depend most heavily on maximal cardiac output, while ultra-endurance events operating at lower fractions of maximum are comparatively less impacted.",
    branch_2: "Criterion 1: Correctly identifies eccentric hypertrophy in endurance athletes — increased chamber volume from volume overload — and concentric hypertrophy in strength athletes — increased wall thickness from pressure overload — as mechanistically opposite cardiac responses to different mechanical demands. Criterion 2: Correctly predicts that a concurrent training athlete develops an intermediate cardiac phenotype with both increased chamber volume and moderate wall thickening rather than one or the other. Criterion 3: Correctly identifies the combined phenotype as advantageous because it provides both high stroke volume from large chamber size and adequate ejection pressure from moderately thickened walls — each modality's cardiac adaptation is additive not competitive.",
    branch_3: "Criterion 1: Correctly identifies peripheral oxygen extraction — the arteriovenous oxygen difference — as the variable explaining why the older trained individual requires more cardiac output per unit of oxygen consumed. Criterion 2: Correctly identifies mitochondrial density, capillary density, and oxidative enzyme activity as the peripheral adaptations responsible for the elite athlete's superior oxygen extraction per unit of blood flow. Criterion 3: Correctly frames the older trained individual's higher cardiac output requirement as reflecting less efficient peripheral oxygen extraction — the heart must pump more blood to deliver the same amount of oxygen to working muscle."
  },
  7: {
    branch_1: "Criterion 1: Correctly identifies higher baseline collagen fibril diameter, collagen density, and greater cross-link maturity in Athlete A's pre-injury ligament as the structural differences produced by years of training — a more robust collagen matrix. Criterion 2: Correctly identifies mechanotransduction through ligamentocyte fibroblast activity as the cellular mechanism — repeated mechanical loading stimulates fibroblasts to produce and organize more and better-quality collagen over training years. Criterion 3: Correctly predicts that the recovered ligament does not fully return to pre-injury structural quality — scar tissue collagen has inferior fiber organization and cross-linking compared to native ligament collagen, even with excellent rehabilitation.",
    branch_2: "Criterion 1: Correctly identifies that stiffer tendons transmit force from muscle to bone more rapidly by reducing the elastic lag — the brief delay while slack tendon takes up before force is transmitted — thereby reducing electromechanical delay. Criterion 2: Correctly identifies rate of force development enhancement — the slope of the force-time curve — as the specific mechanical advantage of tendon stiffness rather than an increase in peak force capacity itself. Criterion 3: Correctly predicts that an athlete with high muscular strength but undertrained tendon stiffness will show a delayed and blunted force-time curve — they eventually produce high force but the rate at which force rises is compromised.",
    branch_3: "Criterion 1: Correctly identifies cyclical loading frequency — the total number of loading cycles — rather than peak force magnitude as the primary driver of tendon collagen synthesis rate. Criterion 2: Correctly identifies that moderate cyclical loading activates tenocyte mechanotransduction more consistently and repeatedly than infrequent high-load events — the accumulated mechanical stimulus over many cycles outweighs intermittent high peaks. Criterion 3: Correctly predicts an optimal return-to-sport tendon conditioning protocol that prioritizes high-repetition moderate-load exercises before progressing to high-load low-repetition work — building collagen synthesis capacity before imposing peak force demands."
  },
  8: {
    branch_1: "Criterion 1: Correctly identifies that neuromuscular adaptations — motor pattern efficiency, calcium handling — and biochemical adaptations — enzyme activity, plasma volume — are suppressed or reduced rather than structurally lost during 4 weeks, enabling rapid restoration once training resumes. Criterion 2: Correctly distinguishes genuinely lost adaptations — such as partial capillary regression and some mitochondrial density reduction — from suppressed or downregulated adaptations that restore faster, explaining why restoration in 3 weeks is possible but not all adaptations recover equally fast. Criterion 3: Correctly predicts that 6-month detraining produces genuine structural regression — significant myonuclear loss, capillary regression, and connective tissue remodeling — requiring a full adaptation timeline to restore, not the rapid 3-week restoration seen after 4 weeks.",
    branch_2: "Criterion 1: Correctly identifies that accumulated fatigue — central nervous system fatigue, connective tissue microtrauma, and hormonal suppression from sustained high volume — masks true strength capacity during the high-volume training phase, making performance appear plateaued when underlying fitness is still improving. Criterion 2: Correctly identifies that maintaining training intensity during a taper preserves the neural drive and fitness signal while the reduction in volume allows the accumulated fatigue to dissipate, unmasking the fitness that was hidden underneath. Criterion 3: Correctly predicts that optimal taper parameters are approximately 2 to 3 weeks duration with 40 to 60 percent volume reduction while keeping intensity at or above pre-taper levels — enough to clear fatigue without allowing significant detraining.",
    branch_3: "Criterion 1: Correctly identifies fatigue dissipation as the primary physiological mechanism of the performance increase — the taper removes accumulated fatigue that was suppressing neuromuscular expression of true fitness. Criterion 2: Correctly distinguishes fitness and fatigue as separate variables that both accumulate during high-volume training — fitness builds slowly, fatigue accumulates faster, and the taper selectively removes fatigue while preserving fitness. Criterion 3: Correctly predicts optimal taper parameters of 2 to 3 weeks duration and approximately 40 to 60 percent volume reduction while maintaining intensity, and identifies that tapers shorter than 2 weeks or longer than 3 weeks are suboptimal for different reasons."
  }
};